import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import time
import math
from datetime import datetime # Get current date and time
from pathlib import Path
from hdf5_dataset_creator_020926 import HDF5IterableDataset
from torch.utils.data import Dataset, DataLoader
import json

#This code estimates the median and percentile values for P-Z normalization using a small subset of the values in the training data.

#Determines whether you are using the original Gaia source catalog files or sharded versions. Options are "Original" and "Shard".
READ_TYPE = "Original"

#Name of normalization data file
NORM_METHOD = 'P_Z_SCORE' #TEST_FRACTION

#Where is the data?
stats_dir = Path("YOUR PATH")
data_dir = 'YOUR PATH/GaiaSource_12182025' #this is where the Gaia hdf5 files must be

#This is the fraction of the test set that you want to use for the test set comparisons
#You will get roughly this amount for each run
#It is applied by shuffling an index for each batch generated by the test loader and then selecting this fraction of that batch
#Note that the full test set has 180 million sources in it, so this fraction should not be very large!
TRAIN_FRACTION = .02

rng = np.random.default_rng()
_ = torch.random.manual_seed(0)

N_WORKERS = 8

#sets batch size for training and validation
batch_size = None
#the columns used in the shard files in the correct order. The ordering for feature_names must match the ordering of the shard files!
shard_columns = None
if READ_TYPE == "Shard":
    assert batch_size is not None, "If using Shard files (i.e., READ_TYPE is Shard), batch_size cannot be None."
    assert batch_size > 0, f"Batch size must be greater than 0. Currently batch size is {batch_size}."
    assert shard_columns is not None, "Must enter columns used in Shard files! shard_columns cannot be None."

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(f"device = {device}")
# Load JSON with float/int normalizations
#with open(stats_dir / "training_stats.json", "r") as f:
#    preprocess = json.load(f)
preprocess = np.load(stats_dir / "P_Z_Norm_Dict_Sample_Ests_w_B_R.npy", allow_pickle = True).item()

hdf5_filelist = np.loadtxt('YOUR PATH/hdf5_filelist.txt', dtype = str)

feature_names = ['pml','pmb']#['ra', 'dec', 'parallax', 'pmra', 'pmdec', 'phot_g_mean_mag', 'phot_bp_mean_mag', 'phot_rp_mean_mag', 'radial_velocity']#list(preprocess['main_train'].keys())
dim = len(feature_names)
print(feature_names)
print(dim)
feature_dict = preprocess.copy()

#Currently I am actually using the validation set for this. Don't use the test until you optimize things
def update_dict(hdf5_filelist, feature_names, feature_dict, batch_size, SET_TYPE, READ_TYPE, TRAIN_FRACTION, dim):
    if SET_TYPE == 'M':
        dict_key_set = 'main_train'
    elif SET_TYPE == 'A':
        dict_key_set = 'subsetA_train'
    elif SET_TYPE == 'B':
        dict_key_set = 'subsetB_train'
    
    test_ds = HDF5IterableDataset(
        READ_TYPE = READ_TYPE,
        filelist = hdf5_filelist,
        split = "train",
        set_type = SET_TYPE,
        columns = feature_names,
        shard_columns = None,
        batch_size = batch_size,
        shuffle_order_each_epoch = False,
        shuffle_sources_in_file = False,
        drop_last = False,
        normalization = feature_dict[dict_key_set],
        norm_method = "NONE", #Take in unnormalized data!
        )
        
    test_loader = DataLoader(
        test_ds,
        num_workers=N_WORKERS,               # start with 4-16 depending on CPU cores
        pin_memory=True,     # keep workers alive between epochs
        drop_last=False,
        )
        
    #this will be slow
    start_loop  = time.time()
    ct = 0
    total_sample_length = 0
    total_test_length = 0
    for x_data, initial_mask in test_loader:
        #x_data/initial_mask --> (1, batch_size, feature_dim)
        x_data_len = x_data.size(dim=1)
        fraction_len = int(TRAIN_FRACTION*x_data_len)
        #print(x_data_len, fraction_len, x_data.shape)
        index = np.arange(x_data_len, dtype = int)
        rng.shuffle(index)
        if ct == 0:
            x_test = torch.empty((fraction_len, 2, dim))
            #print(x_test[:, 0, :].shape, x_data[0,index[:fraction_len], :].shape)
            x_test[:, 0, :] = x_data[0, index[:fraction_len], :]
            x_test[:, 1, :] = initial_mask[0, index[:fraction_len], :]
        else:
            x_temp = torch.empty((fraction_len, 2, dim))
            x_temp[:, 0, :] = x_data[0, index[:fraction_len], :]
            x_temp[:, 1, :] = initial_mask[0, index[:fraction_len], :]
            x_test = torch.cat([x_test, x_temp], dim = 0)
            del x_temp
        ct += 1
        total_test_length += x_data_len
        total_sample_length += fraction_len
    runtime = (time.time() - start_loop)/60
    print(f"Finished constructing sample of training set {SET_TYPE}. Sample fraction set to {TRAIN_FRACTION}. Sample length is {total_sample_length}, total test set length is {total_test_length}, thus the true fraction is {total_sample_length/total_test_length}. Run time is {round(runtime,2)} minutes.")
    del test_loader

    new_feature_dict = feature_dict.copy()
    for c in range(dim):
        mask = x_test[:, 1, c].clone().bool()
        new_feature_dict[dict_key_set][feature_names[c]]['est_median'] = np.nanmedian(x_test[mask, 0, c].numpy())
        new_feature_dict[dict_key_set][feature_names[c]]['est_p2_5'] = np.nanpercentile(x_test[mask, 0, c].numpy(), 2.5)
        new_feature_dict[dict_key_set][feature_names[c]]['est_p97_5'] = np.nanpercentile(x_test[mask, 0, c].numpy(), 97.5)
    del x_test
    
    return new_feature_dict

for SET_TYPE in ['M', 'A', 'B']:
    SET_time = time.time()
    print(f"Beginning {SET_TYPE}")
    if SET_TYPE == 'M':
        dict_key_set = 'main_train'
    elif SET_TYPE == 'A':
        dict_key_set = 'subsetA_train'
    elif SET_TYPE == 'B':
        dict_key_set = 'subsetB_train'

    for c in range(dim):
        if feature_names[c] not in feature_dict[dict_key_set]:
            feature_dict[dict_key_set][feature_names[c]] = {}
    feature_dict = update_dict(hdf5_filelist, feature_names, feature_dict, batch_size, SET_TYPE, READ_TYPE, TRAIN_FRACTION, dim)
    print(f"Finished {SET_TYPE}. Runtime: {time.time() - SET_time}")
    np.save('YOUR PATH/P_Z_Norm_Dict_Sample_Ests_062326.npy', feature_dict)
